version: 2
jobs:
  build-job:
    working_directory: ~/work
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Run tests
          command: ./gradlew clean test coveralls
      - store_test_results:
          path: build/test-results/test

  deploy-job:
    working_directory: ~/work
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Deploy binaries
          command: ./gradlew clean assemble bintrayUpload


workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
            tags:
              only: /v[0-9]+\.[0-9]+\.[0-9]+/

